### ISSUE TITLE
[Bug]: iOS plugin not syncing to WebDAV on WiFi

### ISSUE THREAD

**Issue by exen904** [remotely-save/remotely-save#490]
### What happened?

Hi, I have an issue with the Sync in the iOS plugin using Webdav on a Nextcloud. The sync and connection test are not working anymore while the client is connected to WiFi directly. If I use a cellular connection, it works just fine. That is also the case if I am connected to cellular, but use a VPN back to my network. 

The address of the nextcloud server can be resolved correctly in either case, also the plugin running on Obisidian on my laptop which has the exact same Webdav address also works just fine. I can also open the webdav path in the browser and enter my credentials. So Id say connectivity issues from the iPhone to the nextcloud are not a thing. 

The debug console putput described in the documentation does not seem to be current anymore

`Save Console Logs Into DB` and `Export Console Logs From DB` are not present in the settings of my plugin. 

The connectivity check ends with `webdav server can not be reached` in the exact same moment as `Checking...` appears. If I run the test on cellular/VPN, there is a slight delay which makes a actual running test plausible, not like the 1ms difference between `checking` and `nope`. 

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav (NextCloud)

### Version of the plugin

0.3.38

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by exen904** [comment]
![image](https://github.com/remotely-save/remotely-save/assets/59537420/0b9df341-d66f-459a-99d2-63632a50946f)
![image](https://github.com/remotely-save/remotely-save/assets/59537420/30563583-ddc6-42a8-90ef-84ebd39d8afe)
![image](https://github.com/remotely-save/remotely-save/assets/59537420/f28a5f62-b78c-4710-a256-e0e8cef5711a)
![image](https://github.com/remotely-save/remotely-save/assets/59537420/0b90e11b-c77e-4851-83c0-96e58612836d)

**Comment by fyears** [comment]
I am sure the plugin doesn't know or check the network status, and doesn't change the behavior based on wifi or 4g at all. Actually it just "blindly try to connect".

I would suggest you:

1. Try any plugin of Obsidian that also needs network connection , to see whether the Obsidian app itself has problem.
2. Try another webdav server such as TeraCloud (with generous free quota) **with a test vault** to see any differences.
3. Try to checkout the configuration of your webdav (nextcloud) to see whther you have configured blocking connections from wifi ip address, etc.

**Comment by rainstorms** [comment]
I have the same question. May I ask how it was resolved？

**Comment by exen904** [comment]
Well it didn't for me. Still not working on my iPhone for me, Windows and Linux Clients work just fine with the exact same connection settings.

**Comment by fyears** [comment]
are you using http not https?

**Comment by rainstorms** [comment]
yes.http!

**Comment by fyears** [comment]
> yes.http!

@rainstorms latest obsidian doesn't support http connection any more and you need to sign a valid https certificate of your website

**Comment by rainstorms** [comment]
> > yes.http!
> 
> @rainstorms latest obsidian doesn't support http connection any more and you need to sign a valid https certificate of your website 

Does the latest obsidian have restrictions only for IOS? The PC side is working normally.

**Comment by fyears** [comment]
Yes currently only iOS. And the restriction actually comes from Apple not Obsidian.

**Comment by rainstorms** [comment]
In fact, I don’t quite understand, what is the difference between 5G http and WiFi http?

**Comment by fyears** [comment]
1. the plugin doesn't have any different code for 5g or wifi. it's even not aware of it. if the user finds the device connectable using 5g but not wifi, then i can safely assume that there are some network differences between two network connections, for example some firewall settings somewhere. i am afraid i have no clues and could not help user to debug this situation.

2. in ios, there is difference between http and https. due to the restriction from Apple, Obsidian and the plugin can connect to https, but cannot connect to http.

**Comment by exen904** [comment]
> 1. the plugin doesn't have any different code for 5g or wifi. it's even not aware of it. if the user finds the device connectable using 5g but not wifi, then i can safely assume that there are some network differences between two network connections, for example some firewall settings somewhere. i am afraid i have no clues and could not help user to debug this situation.

Well my biggest issue here is, that I can get no debug information at all that would help here. As the debug information is not present like the documentation makes it appear, as stated in the start of the issue. 

I would absolutely be on par with you on a network issue, if it would make any sense. Which is why I created the issue. When connecting over Wifi, the connection is established as follows:

1. iOS client with IP 192.168.9.x
2. connects to domain https://nextcloud.mydomain.com
3. domain is resolved by interal DNS and points at 192.168.9.x (Ngingx reverse proxy)
4. Ngingx redirects the request to the Nextcloud VM which is located at 192.168.9.x also

All plain L2 networking, no routing over subnets, firewalls etc. 

The same webdav server address (literally copy and pasta) is present at the Windows and Linux client and works just fine there

**Comment by fyears** [comment]
@exen904 yeah sure, thanks for you detailed report.

the debug way is changed now.

would you like to:

1. create a new vault and create some test files
2. install latest **beta version** of remotely save using brat
3. follow this https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/use_logstravaganza.md to export the debug logs

**Comment by fyears** [comment]
and is your domain address https?

if you are connecting using 5g, does the network go through the nginx proxy? i suspect nginx causes some issues

**Comment by exen904** [comment]
@fyears yes, HTTPS is provided through Ngingx via Lets Encrypt. So Ngingx is always in the loop, either via LAN or cellular and independent of the client. 

I also can access the WebUI via iOS in Safari so the config there should be according to the specifications that iOS needs.

**Comment by fyears** [comment]
what's you auth type? basic or digest?

**Comment by xtpcool** [comment]
#292 The issue I'm facing is similar to yours. The solution can be found by using Apache proxy. However, I still hope the author can fix it.

**Comment by fyears** [comment]
> After using Nginx proxy on the PC, it functions properly, but on the iOS, checking the connection prompts an error.

that being said, any **clean, reproducible way** to setup the server and reproduce the error?

**Comment by xtpcool** [comment]
> > After using Nginx proxy on the PC, it functions properly, but on the iOS, checking the connection prompts an error.在PC上使用Nginx代理后，它可以正常工作，但在iOS上，检查连接会提示错误。
> 
> that being said, any **clean, reproducible way** to setup the server and reproduce the error?也就是说，有没有干净的、可重现的方法来设置服务器并重现错误？

My apologies for any confusion. What I meant was that I understand you're facing difficulties with your English. It seems like you've tried reinstalling to reproduce the issue, but you only have one NAS configured with Nginx Proxy Manager. After multiple attempts, only iOS fails. This issue has persisted for a while, and even after the recent updates, you're still encountering the same problem. Currently, you're able to use the built-in reverse proxy on the QNAP NAS for iOS, as it uses Apache.

**Comment by fyears** [comment]
> > > After using Nginx proxy on the PC, it functions properly, but on the iOS, checking the connection prompts an error.
> > 
> > 
> > that being said, any **clean, reproducible way** to setup the server and reproduce the error?
> 
> My English is not very good. If you mean reinstalling to reproduce this problem, I'm sorry, I only have one NAS configured with nginx-proxy-manager. After multiple attempts, only iOS fails. This problem has been like this for a long time. Even after the recent update, I tried and it's still the same. Currently, I'm using the built-in reverse proxy on the NAS, and iOS can be used normally because the reverse proxy built into the QNAP NAS is Apache.

在原贴里用中文回复即可哈。最大的问题是我自己没有 qnap 。有没有办法纯 linux server 复现呢

**Comment by xtpcool** [comment]
> > > > After using Nginx proxy on the PC, it functions properly, but on the iOS, checking the connection prompts an error.
> > > 
> > > 
> > > that being said, any **clean, reproducible way** to setup the server and reproduce the error?
> > 
> > 
> > My English is not very good. If you mean reinstalling to reproduce this problem, I'm sorry, I only have one NAS configured with nginx-proxy-manager. After multiple attempts, only iOS fails. This problem has been like this for a long time. Even after the recent update, I tried and it's still the same. Currently, I'm using the built-in reverse proxy on the NAS, and iOS can be used normally because the reverse proxy built into the QNAP NAS is Apache.
> 
> 在原贴里用中文回复即可哈。最大的问题是我自己没有 qnap 。有没有办法纯 linux server 复现呢

linux搭建个webdav再反向代理对我来说有点困难😓，比较菜所以直接用nas的webdav，我有时间的时候研究下，感谢。

**Comment by fyears** [comment]
你的 apache 能用，nignx 不能用，显然中间有什么配置错误了而不是插件问题，查了一下，可能是一些配置问题 https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2619

**Comment by xtpcool** [comment]
> 你的 apache 能用，nignx 不能用，显然中间有什么配置错误了而不是插件问题，查了一下，可能是一些配置问题 [NginxProxyManager/nginx-proxy-manager#2619](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2619)

但我仅iphone检查连接的时候提示地址或账号密码错误，使用nginx时pc端是可以正常同步的，换用apache手机端才正常😵‍💫

**Comment by xtpcool** [comment]
> 你的 apache 能用，nignx 不能用，显然中间有什么配置错误了而不是插件问题，查了一下，可能是一些配置问题 [NginxProxyManager/nginx-proxy-manager#2619](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2619)

@fyears 解决了！！！您提供了个思路，我也去nginxproxymanager的问题里找了找，只用在nginx里面添加一个参数即可proxy_hide_header Upgrade;

@exen904 To fix just set into Custom Nginx Configuration:
` proxy_hide_header Upgrade;`

**Comment by exen904** [comment]
@xtpcool  already set in my configuration, as well as others:

```
proxy_hide_header Upgrade;
proxy_hide_header X-Powered-By;
add_header Content-Security-Policy "upgrade-insecure-requests";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Cache-Control "no-transform" always;
add_header Referrer-Policy no-referrer always;
add_header X-Robots-Tag none;```

@fyears Im using Basic authentication. Unfortunately I didnt have time to test the beta plugin until now, thats still to be done

**Comment by fyears** [comment]
closed due to no response for a while. feel free to reopen this if you have more clues

**Comment by exen904** [comment]
So quick bump on this, I finally found the issue. Not related to the plugin, but I think documentation should be good if anyone else encounters this. The issue behind everything was iCloud Private Relay in my case. With the Relay active, the DNS request for my configured WebDAV server never got to the internal address while on WiFi, as it was never resolved by my internal DNS server. 

To resolve this, you have to turn off `limit IP Address tracking`, see also https://support.apple.com/en-us/102022

With those settings, my WebDAV Server can now be correctly resolved and the sync works just fine. So it was DNS after all. Thanks a lot for your work on this  great plugin 🙏🏻
